Feature homepage
appiersign/youtube-homepage pull request #2
Opened 2019-12-02 14:16 UTC by appiersign

2019-12-02 14:41 UTC, duducus commented
Good structure, all html semantics is in place. 
the tags can be more descriptive

2019-12-02 23:18 UTC, pelzolga123 commented on style.css
> +}
Empty selector should be deleted.

2019-12-02 23:18 UTC, pelzolga123 commented on index.html
> +                                style="margin-left: -180px">
No inline styling. Please, move all styling to css.

2019-12-02 23:19 UTC, pelzolga123 requested changes
Project needs corrections before it can be approved.

2019-12-02 23:19 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: good!
But there are few things that need to be corrected:
#### General
* [ ] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
* [ ] README.md file is not descriptive.

#### Navbar
* [ ] The search bar should be aligned to the middle of the navbar.  [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/searchbar_align_requirement.png) 
* [ ] It should have at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar. [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png) 

#### Video section
* [ ] It should show the number of views. [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_views_requirement.png)
* [ ] 'Share' should be a button. [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png)
* [ ] 'Subscribe' should be a button. [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png)

###  Please kindly make this changes and send another code review request.

If you have any questions or need help, you can message me on slack. *Happy coding*

2019-12-03 19:40 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2019-12-03 20:17 UTC, Anna-Myzukina commented
### Hi team!

### Nice job! Project looks! :+1: 

The readme file looks good. I hope these links can help make it more professional in the next projects [Professional Github repository](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) and this [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

### But first of all let's fix the few things and we can move on.

#### Page structure

##### Navigation bar steel has few things to change

* [ ] The search bar should be is aligned to the middle of the navbar 

![ ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/searchbar_align_requirement.png)
* [ ] It should has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar 

As we can see, now in your project the search bar steel isn't aligned to the middle of the navbar and three images on the leftmost part, but they should be on rightmost part.
![header](https://user-images.githubusercontent.com/26605804/70085071-3a380f00-1618-11ea-9b0d-02fb40b0b5e6.png)


* Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

2019-12-03 20:21 UTC, Anna-Myzukina requested changes
Kindly recommended make next changes: the search bar still isn't aligned to the middle of the navbar and three images are on the leftmost part, but they should be on the rightmost part.

2019-12-04 18:06 UTC, shshamim63 commented
## Status :recycle: [!! Required Changes !!] :recycle: 
___
Hi @appiersign  & @MotivateJ  :wave: ,
You guys have gathered all the items that are actually needed to decorate the page. There are no  HTML markup error. In one word great job :clap: . But there are some issues that are actually blocking me to approve this project. And i am sure that you guys will fix them easily :sunglasses: .
___
##### Please follow the instructions below :point_down: to declare this project as complete.
___
### :sparkle: [Mandatory Changes] :space_invader: 
___
1. The items on the navbar are not displaying as it should. Is because of declaring with using px. You can look at this [link](https://kyleschaeffer.com/css-font-size-em-vs-px-vs-pt-vs-percent). It will give you clear idea about the units of css properties.
![image](https://user-images.githubusercontent.com/38625956/70167469-f533db80-16f0-11ea-9268-57b16952107b.png)
 This is the view i am getting. Now how can I mimic the environment of the reviewer. Well I use [this](https://responsivedesignchecker.com/) one. So please rearrange the item.
2. The aside items are also breaking their flow.
![image](https://user-images.githubusercontent.com/38625956/70167721-8905a780-16f1-11ea-8c09-e5dda3691086.png)
If you inspect it, you will get the cause. Fix them too.
3. I can see some indentation problem. For an example,
https://github.com/appiersign/youtube-homepage/blob/fbf245a1935b978602403625388282d441ca3150/index.html#L135-L137
<li> open and closing tag should be vertically aligned.
___
### :clubs: [Optional Changes] :clubs: 
___
1. You could use a reset css to reset your browsers default stylesheet. Check this [link](https://stackoverflow.com/questions/11578819/css-reset-what-exactly-does-it-do) for a basic understanding. 
2. There are couple of repetitive codes in css. For an example `width: auto;`. Maybe you can create a class for this and you can use that whenever it is needed.
3. You can make your folder more organized by creating a folder called asstes. Inside that you can create sub folders for different files (image, style(for css)).
4. I think link should appear after all other tags inside head tag.
https://github.com/appiersign/youtube-homepage/blob/fbf245a1935b978602403625388282d441ca3150/index.html#L3-L12
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding:
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

2019-12-04 20:22 UTC, pelzolga123 approved these changes
Approved.

2019-12-04 20:22 UTC, pelzolga123 commented
## Great  work, Congratulation :+1: Project Approved.
### You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

2019-12-04 21:10 UTC, merged